apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    env: dev
  name: hpa-nginx
  namespace: dev
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: deploy-nginx
  targetCPUUtilizationPercentage: 80
